Created wrapper + tests for the Kademlia Library
zimmermatt/ob-winterm24-p2p pull request #22
Opened 2024-01-23 02:36 UTC by thompalex

Modified the peer class by creating a callback function for rpc_store in the Kademlia library to access the key and value.

NewServer overrides the _create_protocol method from Kademlia's network.Server to create an instance of our protocol.

Added tests for our NewServer and NewProtocol -> 100% testing coverage of this code.

2024-01-23 19:12 UTC, zimmermatt requested changes

2024-01-23 19:12 UTC, zimmermatt commented on src/main/py/peer/peer.py
> +        if isinstance(artwork_object, Artwork):
Might be useful to have an `else` that logs that a non-artwork instance, if that's unexpected.

2024-01-23 19:12 UTC, zimmermatt commented on src/main/py/server/network.py
> +class NewServer(Server):
Let's brainstorm some more descriptive names :)

2024-01-23 19:12 UTC, zimmermatt commented on src/main/py/server/protocol.py
> +class NewProtocol(KademliaProtocol):
Let's brainstorm some more descriptive names :)

2024-01-23 19:12 UTC, zimmermatt commented on src/main/py/server/protocol.py
> +        self.callback_function = callback_function
The name for the callback in `NewServer` is better IMO.

2024-01-23 19:12 UTC, zimmermatt commented on src/test/py/server/new_server_test.py
> +        await self.node2.bootstrap([("127.0.0.1", 8468)])
Let's see how it goes, but spinning up/tearing down servers may be a source of instability in the test suite.

2024-01-23 19:12 UTC, zimmermatt commented on src/test/py/server/new_server_test.py
> +        await self.node2.listen(8469)
Please use ports in the dynamic range: 49152 - 65535.

See: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

2024-01-23 21:49 UTC, zimmermatt requested changes
Looking good! Just one comment to take a look at.

Also, it will be helpful if you can point me at the commit with the text you'd like for the squashed merge that covers the entirety of the PR. Or, please write one up that I can use when you push this final change.

2024-01-23 21:49 UTC, zimmermatt commented on src/main/py/peer/peer.py
>          await self.setup_deadline_timer(commission)
This looks like it belongs in the `if set_success:` block as well.

2024-01-23 23:02 UTC, thompalex commented
I think the following will make for a good commit message for the squash:

Subject: Created NotifyingServer and NotificationProtocol for our interaction with the Kademlia module

- NotificationServer and NotificationProtocol run the Kademlia module in the same way as usual, but they take in a callback function for the rpc_store method so that we can listen for and react to new items stored in the DHT. This will allow us to use the DHT as a sort of messaging system between peers.
- Adjusted the current peer class to await necessary asynchronous functions and modified our tests as needed to account for this change.
- Created a preliminary callback function to call on new store requests in our peer class. This callback will evolve to handle different types of "messages" or objects in the DHT as we progress with our goals.

2024-01-24 00:15 UTC, zimmermatt commented on src/test/py/peer/peer_test.py
> +            self.assertEqual(len(self.peer.commissions), 1)
At some point later, a test should be added that tests the failure case and asserts that the commissions count does not increase.

2024-01-24 00:22 UTC, zimmermatt commented
> I think the following will make for a good commit message for the squash:
> 
> Subject: Created NotifyingServer and NotificationProtocol for our interaction with the Kademlia module
> 
> * NotificationServer and NotificationProtocol run the Kademlia module in the same way as usual, but they take in a callback function for the rpc_store method so that we can listen for and react to new items stored in the DHT. This will allow us to use the DHT as a sort of messaging system between peers.
> * Adjusted the current peer class to await necessary asynchronous functions and modified our tests as needed to account for this change.
> * Created a preliminary callback function to call on new store requests in our peer class. This callback will evolve to handle different types of "messages" or objects in the DHT as we progress with our goals.

Looks good. I'm going to make a couple of minor revisions when I merge to comply with the style guide while maintaining the core of your version. Mainly:
* subject <= 50 chars
* imperative mood (guide says "in the subject line" but it also applies to body)

2024-01-24 00:23 UTC, zimmermatt approved these changes

2024-01-24 00:26 UTC, merged